import { useState, createContext, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
    zh: {
        // Layout
        switchThemeLight: '切换到浅色模式',
        switchThemeDark: '切换到深色模式',
        adminPanel: '管理后台',
        logout: '退出登录',
        footerRights: '© 2026 OnePASS. All rights reserved.',
        terms: '使用条款',
        privacy: '隐私政策',
        contact: '联系我们',

        // Verify - header
        welcomeTitle: 'Gemini Pro一年Pixel优惠订阅',
        welcomeDesc: '根据提示提交 Google 账号信息，获取服务',
        programOnline: '程序在线',
        programOffline: '程序离线',
        browserModeLabel: '🌐 浏览器模式',
        apiModeLabel: '⚡ API 模式',
        lastSuccess: '上次成功',
        none: '无',

        // Verify - status badges
        statusReady: '就绪',
        statusProcessing: '处理中',
        statusComplete: '完成',
        statusSubmitting: '提交中...',

        // Verify - service tabs
        geminiVerify: 'Gemini 验证',
        gptRecharge: 'ChatGPT 充值',
        maintenance: '🔧 维护中',

        // Verify - guide section
        guideToggle: '使用教程 & 积分规则',
        creditsRulesTitle: '积分规则 & 邀请奖励',
        geminiStandard: 'Gemini 普通认证',
        geminiPro: 'Gemini 高级认证',
        gptMonthly: 'ChatGPT 月度充值',
        gptTeamInviteRule: 'ChatGPT Team 邀请',
        inviteReward: '邀请奖励',
        inviteRewardVal: '+0.2 积分 / 人',
        inviteNote: '⚠️ 被邀请用户注册后需首次兑换卡密，邀请人才能获得奖励积分',
        creditsUniversal: '✨ 所有服务积分通用，可通过 CDK 兑换或邀请获取',
        geminiServiceTitle: 'Gemini 验证服务',
        geminiServiceDesc: '此服务为通过 Pixel 获取 <strong>Gemini Advanced 1 年 Pro 订阅</strong>，由 OnePASS 全自动完成。',
        guide2faTitle: '2FA 验证：',
        guide2faDesc: '必须开启，并设置好 Google Authenticator',
        guide2faTutorial: '查看教程 ▸',
        guideRegion: '地区要求：',
        guideRegionDesc: '需在支持区域内',
        guideRegionBtn: '查看支持地区 ▸',
        guideRegionTitle: '🌍 支持的国家和地区',
        guideRegionCount: '共 33 个',
        guideFamily: '家庭组：',
        guideFamilyDesc: '必须退出家庭组并确保当前无订阅任何Google one',
        guideAccount: '账号建议：',
        guideAccountDesc: '只能Gmail，建议使用老号，新号极其容易封控，请删除账号付款资料信息',
        guideBindCard: '绑卡注意：',
        guideBindCardDesc: '绑卡时浏览器只能登录你要升级的账号，请先退出其他 Google 账号',
        tierNormal: '普通',
        tierPro: '高级',
        tierNormalDesc: '认证完成后需 <strong>自行绑卡</strong>，如无信用卡可往商城购买',
        tierProDesc: '一条龙服务，认证完成后 <strong>自动绑卡</strong>',
        gptServiceTitle: 'ChatGPT 充值服务',
        gptServiceDesc: '<strong>ChatGPT Plus 月度自动充值</strong>服务，产品无质保。',
        gptGuide1: '获取Session的前提是浏览器已经登陆ChatGPT',
        gptGuide2: '建议会员过期之后再充值',
        gptGuide3: '账号不能加入过Team',

        // Verify - input panel
        inputVerifyLinks: '输入验证链接',
        inputVerifyIds: '输入验证 ID',
        panelTitlePro: '高级提交-自动完成绑卡',
        panelTitleStandard: '普通提交-验证完成之后需自行绑卡',
        tierStandardTab: '📦 普通验证',
        tierProTab: '⚡ 高级验证',
        singleSubmit: '单个提交',
        batchSubmit: '批量提交',
        emailLabel: '账号邮箱',
        passwordLabel: '账号密码',
        totpLabel: '2FA 密钥',
        batchPlaceholder: '邮箱----密码----辅助邮箱----2FA密钥\n或：邮箱----密码----2FA密钥\n\n示例：\ntest@gmail.com----password----backup@mail.com----JBSWY3DPEHPK3PXP\ntest@gmail.com----password----JBSWY3DPEHPK3PXP',
        batchRecognized: '已识别',
        accountUnit: '个账号',
        remaining: '剩余:',
        credits: '积分',
        notLoggedIn: '未登录',
        submitting: '提交中...',
        submitVerify: '🚀 提交验证',

        // Verify - alert messages
        alertLoginFirst: '请先登录后再提交验证',
        alertInsufficientCredits: '账户积分不足（需要 {cost} 积分，当前 {current}）',
        alertFillAll: '请填写所有字段',
        alertInvalidFormat: '请输入有效的账号信息，格式：邮箱----密码----2FA密钥',
        alertGmailOnly: '账号类型错误，只支持 Gmail 邮箱',
        alertTotpNotSecret: '请输入 2FA 密钥（Base32 格式），不是 6 位数字验证码',
        alertAccountSuspended: '判断恶意使用服务，账号已被禁用，如有异议请联系客服',

        textareaPlaceholderTelegram: `粘贴验证链接，每行一个...
例如：
https://services.sheerid.com/verify/67c8c14f5f17a83b745e3f82/?verificationId=699528d723c407520aeadc45

注意：右键复制链接，不要点击打开！
链接验证失败后等待几秒钟刷新页面即可得到新链接。
如果失败之后链接没有重置，可手动到 https://onepass.fun/pass 重置。

验证失败不消耗额度`,
        textareaPlaceholderApi: `粘贴验证 ID 或链接，每行一个...
例如：
699528d723c407520aeadc45
https://services.sheerid.com/verify/...?verificationId=699528d723c407520aeadc45

注意：右键复制链接，不要点击打开！
链接验证失败后等待几秒钟刷新页面即可得到新链接。
如果失败之后链接没有重置，可手动到 https://onepass.fun/pass 重置。

验证失败不消耗额度`,

        // Verify - CDK
        cdkRemaining: 'CDK 剩余额度',
        change: '更改',
        buy: '购买',
        buyCdk: '购买CDK',
        verifying: '验证中...',
        invalidCdk: '❌ 无效',
        linksCount: '个链接',
        idsCount: '个ID',
        remainingQuota: '剩余配额',
        quotaTimes: '次',
        notActivated: '未激活',

        // Verify - actions
        processing: '处理中...',
        startVerify: '🚀 开始验证',

        // Verify - results
        results: '结果',
        clear: '🗑️ 清空',
        export: '📤 导出',
        noResults: '暂无结果',
        noResultsHint: '粘贴验证链接后点击开始',
        resultProcessing: '处理中...',
        stepWarmup: '文档生成中...',
        stepVerify: '提交文档中...',
        stepWaiting: '等待验证...',
        historyTitle: '历史记录',
        verifyResults: '验证结果',
        historyBtn: '📜 历史',
        backBtn: '← 返回',
        clearBtn: '清除',
        refreshBtn: '刷新',
        noHistory: '暂无历史记录',
        noHistoryHint: '提交完成后的结果会自动保存在这里',
        noResultsMsg: '暂无结果',
        noResultsHintAlt: '提交账号信息后，结果将显示在这里',
        copyLink: '复制链接',
        verifySuccess: '验证成功',
        verifyFailed: '验证失败',
        resubmitBtn: '重新提交',

        // Backend messageKey translations
        msgLinkFailed: '该链接已失败，请刷新页面获取新链接',
        msgAlreadyVerified: '该链接已验证成功，无需重复提交',
        msgLinkRejected: '该链接已被拒绝，请刷新页面获取新链接',
        msgWarmupTimeout: '文档生成超时，请重试',
        msgWarmupFailed: '文档生成失败',
        msgVerifyTimeout: '验证超时，请重试',
        msgVerifyFailedRefresh: '验证失败，请刷新页面获取新链接',
        msgFraudDetected: '检测到欺诈行为，请刷新页面获取新链接',
        msgCrashed: '程序崩溃，请重试',
        msgVerifyFailedDetail: '验证失败',
        msgRequestFailed: '请求失败',
        stepFailed: '验证失败，链接刷新中...',
        stepBypass: '链接刷新中...',
        msgBypassDone: '{reason}，链接已刷新，请重新获取新链接',
        msgBypassStarted: '{reason}，链接正在刷新中...',
        msgBypassFailed: '{reason}，请等待几分钟后刷新页面获取新链接',
        reasonFraud: '检测到欺诈',
        reasonDocRejected: '文档被拒绝',
        reasonFailed: '验证失败',

        // Verify - live status
        liveStatusTitle: '📊 实时验证状态',

        // Verify - tips
        tip1pre: '在 ',
        tip1link: 'one.google.com/ai-student',
        tip1post: ' 的蓝色按钮上',
        tip1bold: '右键复制链接',
        tip1end: '，不要点进去！建议用无痕窗口登录账户获取。',
        tip2: '如果验证链接中 verificationId= 后面是空的，建议直接换号。',
        tip3: '一次消耗一个配额，成功后自动扣除。',
        defaultTip1: '📡 提交 Google 账号信息（邮箱、密码、2FA密钥），系统将自动登录并获取 Google One 合作伙伴链接。',
        defaultTip2: '⚠️ 2FA 密钥必须是 Base32 编码的原始密钥（不是 6 位数字验证码）。',
        defaultTip3: '💰 一次消耗一个 CDK 配额，仅在任务成功后扣除。',

        // Format time
        justNow: '刚刚',
        minutesAgo: '分钟前',
        hoursAgo: '小时前',

        // Verify results messages
        msgApproved: '✅ 验证通过！',
        msgRejected: '❌ 验证被拒绝',
        msgError: '❌ 验证出错',
        msgNoCredits: '⚠️ CDK 配额不足',
        msgTimeout: '⏱️ 验证超时，请等待几分钟后刷新链接重试',
        msgApiSuccess: '✅ 验证通过',
        msgApiFail: '❌ ',

        // Verify - polling messages
        submitted: '⏳ 已提交，排队中...',
        queueing: '⏳ 排队中...',
        running: '运行中',
        queuePosition: '排队中',
        fetchSuccess: '✅ 获取成功',
        subscribeSuccess: '✅ 订阅成功',
        processingMsg: '处理中...',
        queueWaiting: '⏳ 排队中 (位置: {pos})',
        cancelJob: '取消任务',
        cancelConfirm: '确定要取消此任务吗？积分将退还到账户',
        cancelSuccess: '任务已取消，积分已退还',
        cancelFailed: '取消失败',
        cancelling: '取消中...',

        // Verify - error descriptions
        errInternalError: '系统内部错误',
        errInternalErrorFirst: '验证失败，请重试',
        errInternalErrorSecond: '账号问题，请查看教程或者联系客服',
        errDeviceUnavailable: '设备不可用',
        errDevicePrepFailed: '设备准备失败',
        errDeviceError: '设备异常',
        errProxyError: '代理连接错误',
        errPasskeyBlocked: '账号要求 Passkey 验证',
        errCaptcha: '遇到人机验证',
        errAccountDisabled: '账号已被停用/锁定',
        errInvalidEmail: '邮箱地址无效',
        errWrongPassword: '密码错误',
        errTotpError: '2FA 密钥错误',
        errNoAuthenticator: '账号未启用 TOTP 验证器',
        errSigninPageFailed: '登录页面加载失败',
        errTwofactorPageError: '两步验证页面异常',
        errGoogleLoginError: 'Google 登录异常',
        errGoogleOneUnavailable: '该账号不可使用 Google One',
        errOfferUnavailable: 'Google One 优惠不可用',
        errAlreadySubscribed: '该账号已有订阅',
        errCardFailed: '信用卡被拒',
        errLoginFailed: '登录失败',
        errNetworkError: '网络连接失败',
        errUrlCaptureFailed: '链接获取失败',
        errSigninFailed: '登录失败',
        errAccountNotDetected: '未检测到账号',
        errBrowserLoginFailed: '浏览器登录失败',
        errManualCancel: '任务被人工取消，请重新提交',
        errInvalidAccount: '账号信息有误，请检查账号密码/2FA密钥',
        errUnknownError: '未知错误',
        errServiceUnavailable: '服务暂时不可用，请稍后重试',
        errGenericFailed: '操作失败，请稍后重试',

        // GPT recharge
        gptPanelTitle: 'ChatGPT Plus 月度充值',
        gptCostBadge: '⚡ 3 积分 / 次',
        gptModePlus: '🤖 Plus 充值',
        gptModeTeam: '👥 Team 邀请',
        gptTeamPanelTitle: 'ChatGPT Team 邀请',
        gptTeamCostBadge: '⚡ 0.6 积分 / 次',
        gptPasteSession: '粘贴 ChatGPT Session',
        gptGetSession: '🔗 获取 Session',
        gptHelp1: '在浏览器登录 ChatGPT',
        gptHelp2: '点击上方「获取 Session」按钮',
        gptHelp3: '复制内容粘贴到下方',
        gptParseError: '无法识别账号，请确保粘贴了完整的 Session JSON',
        gptAccountLinked: '已绑定 ChatGPT 账号',
        gptChangeAccount: '更换',
        gptStartRecharge: '⚡ 开始充值',
        gptRecharging: '正在充值，请稍候...',
        gptInsufficientCredits: '积分不足，需要 3 积分，当前剩余 {credits} 积分',
        gptCardExchangeFailed: '卡密兑换失败',
        gptRechargeFailed: '充值失败，请稍后重试',
        gptRechargeSuccess: '充值成功！',
        gptRechargeHistoryTitle: '充值历史',
        gptRechargeResultTitle: '充值结果',
        gptPanelHistoryTitle: 'Plus 充值记录',
        gptTeamPanelHistoryTitle: 'Team 邀请记录',
        gptNoHistory: '暂无充值记录',
        gptNoHistoryHint: '充值完成后的结果会显示在这里',
        gptSuccessTitle: '充值成功！',
        gptSuccessDesc: '账号 <strong>{email}</strong> 已成功充值 ChatGPT Plus',
        gptContinue: '继续充值',
        gptResultHint: '📡 粘贴 ChatGPT Session 信息后点击充值按钮',
        gptResultNote: '⚠️ 请确保 ChatGPT 已登录，充值成功后扣除 3 积分',
        gptRechargingMsg: '充值进行中，请稍候...',
        gptTeamInviteEmail: '输入被邀请邮箱',
        gptTeamInvitePlaceholder: 'member@example.com',
        gptTeamInviteNote: '系统会自动选择有空位的 Team 发送邀请，邀请创建成功后扣除 0.6 积分。',
        gptTeamStartInvite: '✉️ 发送 Team 邀请',
        gptTeamInviting: '正在发送邀请，请稍候...',
        gptTeamInvitingMsg: '正在创建 Team 邀请，请稍候...',
        gptTeamInsufficientCredits: '积分不足，需要 0.6 积分，当前剩余 {credits} 积分',
        gptTeamInviteFailed: 'Team 邀请失败，请稍后重试',
        gptTeamInviteSuccess: 'Team 邀请发送成功！',
        gptTeamResultHint: '📨 输入被邀请邮箱后点击发送按钮',
        gptTeamResultNote: '⚠️ 邀请成功创建后扣除 0.6 积分，邮件投递可能有延迟',
        gptTeamSuccessTitle: 'Team 邀请成功！',
        gptTeamSuccessDesc: '邮箱 <strong>{email}</strong> 已成功加入待邀请列表',
        rechargeSuccess: '充值成功',
        rechargeFailed: '充值失败',

        // CDK Redeem
        redeemCredits: '兑换积分',
        purchaseCredits: '购买积分',
        cdkRedeemTitle: '兑换积分',
        cdkRedeemSubtitle: '输入 CDK 卡密，积分将充入您的账户',
        cdkRedeem: '兑换',
        cdkRedeemHint: '从 <a>haodongxi.shop</a> 购买 CDK 卡密后在此兑换',
        cdkLoginFirst: '请先登录后再兑换积分',
        cdkRedeemFailed: '兑换失败',
        cdkNetworkError: '网络错误，请稍后重试',

        // Verify - region list (Chinese)
        regionAustralia: '🇦🇺 澳洲', regionAustria: '🇦🇹 奥地利', regionBelgium: '🇧🇪 比利时',
        regionCanada: '🇨🇦 加拿大', regionCzechia: '🇨🇿 捷克', regionDenmark: '🇩🇰 丹麦',
        regionEstonia: '🇪🇪 爱沙尼亚', regionFinland: '🇫🇮 芬兰', regionFrance: '🇫🇷 法国',
        regionGermany: '🇩🇪 德国', regionHungary: '🇭🇺 匈牙利', regionIndia: '🇮🇳 印度',
        regionIreland: '🇮🇪 爱尔兰', regionItaly: '🇮🇹 意大利', regionJapan: '🇯🇵 日本',
        regionLatvia: '🇱🇻 拉脱维亚', regionLithuania: '🇱🇹 立陶宛', regionMalaysia: '🇲🇾 马来西亚',
        regionMexico: '🇲🇽 墨西哥', regionNetherlands: '🇳🇱 荷兰', regionNorway: '🇳🇴 挪威',
        regionPoland: '🇵🇱 波兰', regionPortugal: '🇵🇹 葡萄牙', regionRomania: '🇷🇴 罗马尼亚',
        regionSingapore: '🇸🇬 新加坡', regionSlovakia: '🇸🇰 斯洛伐克', regionSlovenia: '🇸🇮 斯洛维尼亚',
        regionSpain: '🇪🇸 西班牙', regionSweden: '🇸🇪 瑞典', regionSwitzerland: '🇨🇭 瑞士',
        regionTaiwan: '🇹🇼 台湾', regionUK: '🇬🇧 英国', regionUS: '🇺🇸 美国',

        // Admin - page
        adminTitle: '⚙️ 管理后台',
        adminDesc: '管理用户、配置系统和查看统计数据',

        // Admin - tabs
        tabOverview: '概览',
        tabCdk: 'CDK 管理',
        tabUsers: '用户管理',
        tabAiGen: 'AI 文档生成',
        tabVerifyStatus: '验证状态',
        tabTgBot: '验证 Bot',
        tabSettings: '系统设置',

        // Admin - overview stats
        statTotalSuccess: '总验证成功',
        stat1hRate: '1小时成功率',
        stat5hRate: '5小时成功率',
        statApiUsage: 'API 消耗',
        statLocalUsage: '本地消耗',

        // Admin - verify log
        logTotal: '共',
        logEntries: '条',
        logSuccess: '成功',
        logFailed: '失败',
        logNoRecords: '暂无验证记录',

        // Admin - telegram bot sections
        tgStats: '📊 统计',
        tgVerifyLog: '📋 验证日志',
        tgConfig: '⚙️ 配置',
        tgServices: '📋 服务',
        tgUsers: '👥 用户',
        tgOrders: '💰 订单',
        tgNoBotLog: '暂无 Bot 验证记录',

        // Admin common
        loading: '⏳ 加载中...',
        save: '保存',
        saving: '保存中...',
        refresh: '🔄',

        // Layout & CDK Redeeming
        redeemCreditsSuccess: '✅ 兑换成功！+{credits} 积分',
        networkError: '网络错误，请重试',
        creditsBalance: '积分余额',
        redeemCreditsTitle: '🎁 兑换积分',
        redeemBtn: '兑换',
        purchaseCreditsTitle: '🛒 购买积分',
        inviteFriends: '邀请好友',
        inviteBtn: '邀请',
        inviteFriendsEarn: '🎁 邀请好友赚积分',
        inviteDesc: '好友通过你的链接注册并购买积分后，你获得 <strong>+0.2 积分</strong>',
        copied: '✓ 已复制',
        copy: '复制',
        invitedCountLabel: '已邀请',
        earnedCreditsLabel: '获得积分',
        recentInvites: '最近邀请记录',
        rewardedStatus: '✓ 已返利',
        pendingStatus: '待购买',
        noInvitesYet: '还没有邀请记录，分享链接给好友吧 🚀',
        loginToInvite: '登录 后即可获取邀请链接',
        apiDocsLink: 'API 文档',
        customerServiceTitle: '客服',
        contactCustomerService: '联系客服',
        scanQrContact: '扫码联系客服',
        csAccountLabel: '客服账号',

        // Verify Page
        tutorialsAndErrors: '教程和常见错误',
        tutorialBindCardBtn: '绑卡教程 ▸',
        commonErrorsWarning: '⚠️ 常见错误都是未开启2FA和未删除付款资料',
        gptRechargeWaitNote: '充值完成后积分自动扣除，请耐心等待',

        // Home (Login/Register) Page
        forgotLinkSent: '重置链接已发送到您的邮箱',
        forgotLinkFailed: '发送失败，请稍后重试',
        featureCreditsTitle: '账户积分系统',
        featureCreditsDesc: '购买 CDK 卡密兑换积分到账户，积分统一管理，随用随扣',
        featureVerifyDesc: '批量提交 Google 账号信息，系统将自动开始升级',
        featureGptDesc: '一键为 ChatGPT Plus 账户充值，自动获取升级',
        featureInviteTitle: '邀请返利',
        featureInviteDesc: '邀请好友注册，双方都可获得积分奖励',
        heroBadgeText: '领先的验证自动化平台',
        heroTitleText: '批量自动化验证工具',
        heroDescText: '一站式 Google One 学生验证 & GPT 充值平台。注册账户后使用 CDK 卡密兑换积分，随用随扣。',
        statVerified: '成功验证',
        statRate: '成功率',
        statServices: '在线服务',
        loginTab: '登录',
        registerTab: '注册',
        usernameLabel: '用户名',
        usernamePlaceholder: '输入用户名',
        emailPlaceholder: '输入邮箱',
        passwordPlaceholder: '输入密码',
        invitePlaceholder: '邀请码（选填）',
        btnRegister: '创建账户',
        forgotPasswordBtn: '忘记密码？',
        resetPasswordTitle: '🔑 重置密码',
        resetPasswordDesc: '输入您注册时使用的邮箱，我们将向您发送重置密码的链接',
        cancelBtn: '取消',
        sendingBtn: '发送中...',
        sendResetLinkBtn: '发送重置链接',
        stepRegisterTitle: '注册 / 登录账户',
        stepRegisterDesc: '创建您的 OnePASS 账户，所有积分 and 记录统一管理',
        stepRedeemTitle: '购买并兑换 CDK',
        stepRedeemDesc: '购买 CDK 卡密并兑换到您的账户，系统自动扣款',
        stepSubmitTitle: '提交验证 / 充值',
        stepSubmitDesc: '选择您要的服务，根据指引输入，系统自动完成',

        // Profile Page
        tabPersonalInfo: '个人信息',
        tabQuotaHistory: '配额记录',
        tabVerifyRecords: '验证记录',
        tabSecuritySettings: '安全设置',
        alertPasswordsMismatch: '两次输入的密码不一致',
        alertPasswordLength: '密码长度至少6位',
        alertPasswordSuccess: '密码修改成功',
        roleAdmin: '👑 管理员',
        roleUser: '👤 普通用户',
        roleAdminLabel: '管理员',
        roleUserLabel: '普通用户',
        quotaBalance: '配额余额',
        totalVerificationsLabel: '总验证次数',
        basicInfoTitle: '👤 基本信息',
        regTime: '注册时间',
        quotaUsageHistoryTitle: '🎫 配额使用记录',
        currentBalanceUnit: '当前余额: <strong>{credits} 次</strong>',
        thDate: '日期',
        thAction: '操作',
        thChange: '变动',
        thBalance: '余额',
        timesUnit: '次',
        regGift: '注册赠送',
        rechargeAction: '充值',
        thVerifyId: '验证ID',
        thStatus: '状态',
        thTime: '时间',
        editBtn: '修改',
        exitBtn: '退出',
        changePasswordTitle: '🔐 修改密码',
        confirmChangeBtn: '确认修改',
        labelCurrentPassword: '当前密码',
        labelNewPassword: '新密码',
        labelConfirmNewPassword: '确认新密码',

        // Recharge Page
        rechargeSuccessAlert: '充值成功！已获得 {quota} 次配额',
        rechargeQuotaTitle: '💰 充值配额',
        rechargeQuotaDesc: '选择适合您的套餐，获取验证配额',
        currentBalanceLabel: '当前余额',
        mostPopular: '🔥 最受欢迎',
        buyNowBtn: '立即购买',
        whyChooseRechargeTitle: '为什么选择我们的充值服务？',
        featureInstantTitle: '即时到账',
        featureInstantDesc: '支付完成后，配额将立即充值到您的账户，无需等待',
        featureSecureTitle: '安全支付',
        featureSecureDesc: '采用官方支付通道，保障您的资金与账户安全',
        featureDiscountTitle: '买多更优惠',
        featureDiscountDesc: '大额套餐享有更高的折扣，验证越多越划算',
        featureCsTitle: '7×24 客服支持',
        featureCsDesc: '充值过程中遇到任何问题，客服团队随时为您解答',
        confirmOrderTitle: '确认订单',
        payableAmount: '应付金额',
        selectPaymentMethod: '选择支付方式',
        alipay: '支付宝',
        wechatPay: '微信支付',
        processingPayment: '正在处理支付...',

        // Bypass Page
        connectError: '连接错误: {error}',
        executing: '执行中...',
        startBypass: '开始 Bypass',
        uploadCount: '成功上传 {uploads} 次',
        linkAlreadySuccess: '链接已是成功状态',
        bypassFailed: 'Bypass 失败',
        waitingOp: '等待操作...',

        // Maintenance Page
        underMaintenance: '维护中',
        maintenanceMsg: '系统维护中，请稍后再试',
        etaLabel: '预计恢复时间: {time}',
        maintenanceSub: '我们正在进行系统升级，请稍后访问',

        // ResetPassword Page
        resetPasswordAlertLength: '密码长度不能少于 6 位',
        resetPasswordAlertMismatch: '两次输入的密码不一致',
        resetPasswordFailed: '重置失败',
        invalidResetLinkTitle: '无效的重置链接',
        invalidResetLinkDesc: '请从邮件中重新点击重置链接，或重新发起密码重置申请',
        btnGoToLogin: '返回登录',
        setNewPasswordTitle: '设置新密码',
        setNewPasswordDesc: '请输入您的新密码',
        resetSuccessTitle: '密码重置成功！',
        resetSuccessDesc: '您的密码已更新，请使用新密码登录',
        goToLoginBtn: '前往登录',
        newPasswordLabel: '新密码',
        min6Chars: '至少 6 位',
        confirmNewPasswordLabel: '确认新密码',
        inputNewPasswordAgain: '再次输入新密码',
        resetPasswordBtn: '重置密码',
        backToLoginBtn: '返回登录页面',
    },
    en: {
        // Layout
        switchThemeLight: 'Switch to Light Mode',
        switchThemeDark: 'Switch to Dark Mode',
        adminPanel: 'Admin Panel',
        logout: 'Log Out',
        footerRights: '© 2026 OnePASS. All rights reserved.',
        terms: 'Terms of Use',
        privacy: 'Privacy Policy',
        contact: 'Contact Us',

        // Verify - header
        welcomeTitle: 'Self-Service AI Platform',
        welcomeDesc: 'Submit Google account info as prompted to get started',
        programOnline: 'Online',
        programOffline: 'Offline',
        browserModeLabel: '🌐 Browser Mode',
        apiModeLabel: '⚡ API Mode',
        lastSuccess: 'Last success',
        none: 'None',

        // Verify - status badges
        statusReady: 'Ready',
        statusProcessing: 'Processing',
        statusComplete: 'Complete',
        statusSubmitting: 'Submitting...',

        // Verify - service tabs
        geminiVerify: 'Gemini Verify',
        gptRecharge: 'ChatGPT Recharge',
        maintenance: '🔧 Maintenance',

        // Verify - guide section
        guideToggle: 'Tutorial & Credit Rules',
        creditsRulesTitle: 'Credit Rules & Referral Rewards',
        geminiStandard: 'Gemini Standard',
        geminiPro: 'Gemini Pro',
        gptMonthly: 'ChatGPT Monthly Recharge',
        gptTeamInviteRule: 'ChatGPT Team Invite',
        inviteReward: 'Referral Reward',
        inviteRewardVal: '+0.2 credits / person',
        inviteNote: '⚠️ Invited users must redeem a CDK after registration for the referrer to receive the reward',
        creditsUniversal: '✨ Credits are universal across all services. Get them via CDK or referrals',
        geminiServiceTitle: 'Gemini Verification Service',
        geminiServiceDesc: 'This service obtains a <strong>1-year Gemini Advanced Pro subscription</strong> via Pixel, fully automated by OnePASS.',
        guide2faTitle: '2FA Required:',
        guide2faDesc: 'Must be enabled with Google Authenticator set up',
        guide2faTutorial: 'View Tutorial ▸',
        guideRegion: 'Region Requirement:',
        guideRegionDesc: 'Must be in a supported region',
        guideRegionBtn: 'View Supported Regions ▸',
        guideRegionTitle: '🌍 Supported Countries & Regions',
        guideRegionCount: '33 total',
        guideFamily: 'Family Group:',
        guideFamilyDesc: 'Must leave family group, ensure no prior subscription',
        guideAccount: 'Account Tip:',
        guideAccountDesc: 'Use an aged account. New accounts are easily flagged and may get locked',
        guideBindCard: 'Card Binding Note:',
        guideBindCardDesc: 'Only log in with the account you want to upgrade. Sign out of other Google accounts first',
        tierNormal: 'Standard',
        tierPro: 'Pro',
        tierNormalDesc: 'After verification, you need to <strong>bind a card yourself</strong>. Buy one from the store if needed',
        tierProDesc: 'Full service — <strong>auto card binding</strong> after verification',
        gptServiceTitle: 'ChatGPT Recharge Service',
        gptServiceDesc: '<strong>ChatGPT Plus monthly auto-recharge</strong> service. No warranty.',
        gptGuide1: 'You must be logged in to ChatGPT in your browser to get the Session',
        gptGuide2: 'It is recommended to recharge after your membership expires',
        gptGuide3: 'Account must not have joined any Team',

        // Verify - input panel
        inputVerifyLinks: 'Enter Verification Links',
        inputVerifyIds: 'Enter Verification IDs',
        panelTitlePro: 'Pro Submit — Auto Card Binding',
        panelTitleStandard: 'Standard Submit — Manual Card Binding After Verification',
        tierStandardTab: '📦 Standard',
        tierProTab: '⚡ Pro',
        singleSubmit: 'Single',
        batchSubmit: 'Batch',
        emailLabel: 'Email',
        passwordLabel: 'Password',
        totpLabel: '2FA Secret Key',
        batchPlaceholder: 'email----password----backup_email----2FA_secret\nor: email----password----2FA_secret\n\nExample:\ntest@gmail.com----password----backup@mail.com----JBSWY3DPEHPK3PXP\ntest@gmail.com----password----JBSWY3DPEHPK3PXP',
        batchRecognized: 'Recognized',
        accountUnit: 'account(s)',
        remaining: 'Remaining:',
        credits: 'credits',
        notLoggedIn: 'Not logged in',
        submitting: 'Submitting...',
        submitVerify: '🚀 Submit',

        // Verify - alert messages
        alertLoginFirst: 'Please log in before submitting verification',
        alertInsufficientCredits: 'Insufficient credits (need {cost}, current {current})',
        alertFillAll: 'Please fill in all fields',
        alertInvalidFormat: 'Please enter valid account info. Format: email----password----2FA_secret',
        alertGmailOnly: 'Invalid account type, only Gmail accounts are supported',
        alertTotpNotSecret: 'Please enter the 2FA secret key (Base32 format), not the 6-digit verification code',
        alertAccountSuspended: 'Malicious usage detected. Your account has been suspended. Please contact support if you have any concerns.',

        textareaPlaceholderTelegram: `Paste verification links, one per line...

Example:
https://services.sheerid.com/verify/67c8c14f5f17a83b745e3f82/?verificationId=699528d723c407520aeadc45

⚠️ Note: Right-click to copy the link, don't click it!`,
        textareaPlaceholderApi: `Paste verification IDs or links, one per line...
Example:
699528d723c407520aeadc45
https://services.sheerid.com/verify/...?verificationId=699528d723c407520aeadc45

After a link verification fails, wait a few seconds and refresh the page to get a new link.
If the link is not reset after a failure, you can manually reset it at https://onepass.fun/pass.

Failed verification does not consume quota.`,

        // Verify - CDK
        cdkRemaining: 'CDK Remaining',
        change: 'Change',
        buy: 'Buy',
        buyCdk: 'Buy CDK',
        verifying: 'Verifying...',
        invalidCdk: '❌ Invalid',
        linksCount: ' link(s)',
        idsCount: ' ID(s)',
        remainingQuota: 'Remaining',
        quotaTimes: '',
        notActivated: 'Not activated',

        // Verify - actions
        processing: 'Processing...',
        startVerify: '🚀 Start Verify',

        // Verify - results
        results: 'Results',
        clear: '🗑️ Clear',
        export: '📤 Export',
        noResults: 'No results yet',
        noResultsHint: 'Paste verification links and click Start',
        resultProcessing: 'Processing...',
        stepWarmup: 'Generating document...',
        stepVerify: 'Submitting document...',
        stepWaiting: 'Waiting for verification...',
        historyTitle: 'History',
        verifyResults: 'Verification Results',
        historyBtn: '📜 History',
        backBtn: '← Back',
        clearBtn: 'Clear',
        refreshBtn: 'Refresh',
        noHistory: 'No history yet',
        noHistoryHint: 'Completed results will be automatically saved here',
        noResultsMsg: 'No results yet',
        noResultsHintAlt: 'Results will appear here after submission',
        copyLink: 'Copy link',
        verifySuccess: 'Verification passed',
        verifyFailed: 'Verification failed',
        resubmitBtn: 'Re-submit',

        // Backend messageKey translations
        msgLinkFailed: 'Link already failed, please refresh for a new link',
        msgAlreadyVerified: 'Link already verified, no need to resubmit',
        msgLinkRejected: 'Link already rejected, please refresh for a new link',
        msgWarmupTimeout: 'Document generation timed out, please retry',
        msgWarmupFailed: 'Document generation failed',
        msgVerifyTimeout: 'Verification timed out, please retry',
        msgVerifyFailedRefresh: 'Verification failed, please refresh for a new link',
        msgFraudDetected: 'Fraud detected, please refresh for a new link',
        msgCrashed: 'Program crashed, please retry',
        msgVerifyFailedDetail: 'Verification failed',
        msgRequestFailed: 'Request failed',
        stepFailed: 'Verification failed, refreshing link...',
        stepBypass: 'Refreshing link...',
        msgBypassDone: '{reason}, link refreshed, please get a new link',
        msgBypassStarted: '{reason}, link is being refreshed...',
        msgBypassFailed: '{reason}, please wait a few minutes then refresh for a new link',
        reasonFraud: 'Fraud detected',
        reasonDocRejected: 'Document rejected',
        reasonFailed: 'Verification failed',

        // Verify - live status
        liveStatusTitle: '📊 Live Verification Status',

        // Verify - tips
        tip1pre: 'Right-click the blue button on ',
        tip1link: 'one.google.com/ai-student',
        tip1post: ' to ',
        tip1bold: 'copy the link',
        tip1end: ", don't click it! Use incognito to get the link.",
        tip2: 'If verificationId= is empty in the link, try a different account.',
        tip3: 'Each verification uses 1 quota, deducted after success.',
        defaultTip1: '📡 Submit Google account info (email, password, 2FA secret). The system will auto-login and obtain the Google One partner link.',
        defaultTip2: '⚠️ The 2FA secret must be the raw Base32 key (not the 6-digit code).',
        defaultTip3: '💰 Each task consumes 1 CDK quota, deducted only on success.',

        // Format time
        justNow: 'Just now',
        minutesAgo: 'm ago',
        hoursAgo: 'h ago',

        // Verify results messages
        msgApproved: '✅ Approved!',
        msgRejected: '❌ Rejected',
        msgError: '❌ Error',
        msgNoCredits: '⚠️ Insufficient CDK credits',
        msgTimeout: '⏱️ Verification timed out. Please wait a few minutes and try again with a refreshed link',
        msgApiSuccess: '✅ Approved',
        msgApiFail: '❌ ',

        // Verify - polling messages
        submitted: '⏳ Submitted, queuing...',
        queueing: '⏳ Queuing...',
        running: 'Running',
        queuePosition: 'In queue',
        fetchSuccess: '✅ Success',
        subscribeSuccess: '✅ Subscribed',
        processingMsg: 'Processing...',
        queueWaiting: '⏳ In queue (position: {pos})',
        cancelJob: 'Cancel',
        cancelConfirm: 'Are you sure you want to cancel this job? Credits will be refunded.',
        cancelSuccess: 'Job cancelled, credits refunded',
        cancelFailed: 'Cancel failed',
        cancelling: 'Cancelling...',

        // Verify - error descriptions
        errInternalError: 'Internal system error',
        errInternalErrorFirst: 'Verification failed, please retry',
        errInternalErrorSecond: 'Account issue, please check the tutorial or contact support',
        errDeviceUnavailable: 'Device unavailable',
        errDevicePrepFailed: 'Device preparation failed',
        errDeviceError: 'Device error',
        errProxyError: 'Proxy connection error',
        errPasskeyBlocked: 'Account requires Passkey verification',
        errCaptcha: 'CAPTCHA encountered',
        errAccountDisabled: 'Account disabled/locked',
        errInvalidEmail: 'Invalid email address',
        errWrongPassword: 'Wrong password',
        errTotpError: '2FA secret key error',
        errNoAuthenticator: 'TOTP authenticator not enabled',
        errSigninPageFailed: 'Sign-in page failed to load',
        errTwofactorPageError: '2FA page error',
        errGoogleLoginError: 'Google login error',
        errGoogleOneUnavailable: 'Google One unavailable for this account',
        errOfferUnavailable: 'Google One offer unavailable',
        errAlreadySubscribed: 'Account already has a subscription',
        errCardFailed: 'Credit card declined',
        errLoginFailed: 'Login failed',
        errNetworkError: 'Network connection failed',
        errUrlCaptureFailed: 'URL capture failed',
        errSigninFailed: 'Sign-in failed',
        errAccountNotDetected: 'Account not detected',
        errBrowserLoginFailed: 'Browser login failed',
        errManualCancel: 'Task manually cancelled, please resubmit',
        errInvalidAccount: 'Account info incorrect, please check your credentials/2FA',
        errUnknownError: 'Unknown error',
        errServiceUnavailable: 'Service temporarily unavailable, please try again later',
        errGenericFailed: 'Operation failed, please try again later',

        // GPT recharge
        gptPanelTitle: 'ChatGPT Plus Monthly Recharge',
        gptCostBadge: '⚡ 3 credits / time',
        gptModePlus: '🤖 Plus Recharge',
        gptModeTeam: '👥 Team Invite',
        gptTeamPanelTitle: 'ChatGPT Team Invite',
        gptTeamCostBadge: '⚡ 0.6 credits / time',
        gptPasteSession: 'Paste ChatGPT Session',
        gptGetSession: '🔗 Get Session',
        gptHelp1: 'Log in to ChatGPT in your browser',
        gptHelp2: 'Click the "Get Session" button above',
        gptHelp3: 'Copy and paste the content below',
        gptParseError: 'Cannot identify account. Please paste the complete Session JSON',
        gptAccountLinked: 'Linked ChatGPT Account',
        gptChangeAccount: 'Change',
        gptStartRecharge: '⚡ Start Recharge',
        gptRecharging: 'Recharging, please wait...',
        gptInsufficientCredits: 'Insufficient credits. Need 3, current balance: {credits}',
        gptCardExchangeFailed: 'Card key exchange failed',
        gptRechargeFailed: 'Recharge failed, please try again later',
        gptRechargeSuccess: 'Recharge successful!',
        gptRechargeHistoryTitle: 'Recharge History',
        gptRechargeResultTitle: 'Recharge Result',
        gptPanelHistoryTitle: 'Plus Recharge Records',
        gptTeamPanelHistoryTitle: 'Team Invite Records',
        gptNoHistory: 'No recharge records',
        gptNoHistoryHint: 'Results will appear here after recharge',
        gptSuccessTitle: 'Recharge Successful!',
        gptSuccessDesc: 'Account <strong>{email}</strong> has been recharged with ChatGPT Plus',
        gptContinue: 'Continue Recharging',
        gptResultHint: '📡 Paste ChatGPT Session info then click the recharge button',
        gptResultNote: '⚠️ Make sure you are logged in to ChatGPT. 3 credits will be deducted on success',
        gptRechargingMsg: 'Recharge in progress, please wait...',
        gptTeamInviteEmail: 'Invitee Email',
        gptTeamInvitePlaceholder: 'member@example.com',
        gptTeamInviteNote: 'The system will automatically pick a Team with available seats and create an invite. 0.6 credits are deducted after success.',
        gptTeamStartInvite: '✉️ Send Team Invite',
        gptTeamInviting: 'Sending invite, please wait...',
        gptTeamInvitingMsg: 'Creating Team invite, please wait...',
        gptTeamInsufficientCredits: 'Insufficient credits. Need 0.6, current balance: {credits}',
        gptTeamInviteFailed: 'Team invite failed, please try again later',
        gptTeamInviteSuccess: 'Team invite sent successfully!',
        gptTeamResultHint: '📨 Enter the invitee email and click the send button',
        gptTeamResultNote: '⚠️ 0.6 credits are deducted after the invite is created successfully. Email delivery may be delayed',
        gptTeamSuccessTitle: 'Team Invite Successful!',
        gptTeamSuccessDesc: 'Email <strong>{email}</strong> has been added to the pending invite list',
        rechargeSuccess: 'Recharge successful',
        rechargeFailed: 'Recharge failed',

        // CDK Redeem
        redeemCredits: 'Redeem Credits',
        purchaseCredits: 'Buy Credits',
        cdkRedeemTitle: 'Redeem Credits',
        cdkRedeemSubtitle: 'Enter a CDK code to add credits to your account',
        cdkRedeem: 'Redeem',
        cdkRedeemHint: 'Purchase CDK codes from <a>haodongxi.shop</a> and redeem here',
        cdkLoginFirst: 'Please log in before redeeming credits',
        cdkRedeemFailed: 'Redemption failed',
        cdkNetworkError: 'Network error, please try again later',

        // Verify - region list (English)
        regionAustralia: '🇦🇺 Australia', regionAustria: '🇦🇹 Austria', regionBelgium: '🇧🇪 Belgium',
        regionCanada: '🇨🇦 Canada', regionCzechia: '🇨🇿 Czechia', regionDenmark: '🇩🇰 Denmark',
        regionEstonia: '🇪🇪 Estonia', regionFinland: '🇫🇮 Finland', regionFrance: '🇫🇷 France',
        regionGermany: '🇩🇪 Germany', regionHungary: '🇭🇺 Hungary', regionIndia: '🇮🇳 India',
        regionIreland: '🇮🇪 Ireland', regionItaly: '🇮🇹 Italy', regionJapan: '🇯🇵 Japan',
        regionLatvia: '🇱🇻 Latvia', regionLithuania: '🇱🇹 Lithuania', regionMalaysia: '🇲🇾 Malaysia',
        regionMexico: '🇲🇽 Mexico', regionNetherlands: '🇳🇱 Netherlands', regionNorway: '🇳🇴 Norway',
        regionPoland: '🇵🇱 Poland', regionPortugal: '🇵🇹 Portugal', regionRomania: '🇷🇴 Romania',
        regionSingapore: '🇸🇬 Singapore', regionSlovakia: '🇸🇰 Slovakia', regionSlovenia: '🇸🇮 Slovenia',
        regionSpain: '🇪🇸 Spain', regionSweden: '🇸🇪 Sweden', regionSwitzerland: '🇨🇭 Switzerland',
        regionTaiwan: '🇹🇼 Taiwan', regionUK: '🇬🇧 United Kingdom', regionUS: '🇺🇸 United States',

        // Admin - page
        adminTitle: '⚙️ Admin Dashboard',
        adminDesc: 'Manage users, configure system, and view analytics',

        // Admin - tabs
        tabOverview: 'Overview',
        tabCdk: 'CDK Management',
        tabUsers: 'User Management',
        tabAiGen: 'AI Doc Generator',
        tabVerifyStatus: 'Verify Status',
        tabTgBot: 'Verify Bot',
        tabSettings: 'Settings',

        // Admin - overview stats
        statTotalSuccess: 'Total Verified',
        stat1hRate: '1h Success Rate',
        stat5hRate: '5h Success Rate',
        statApiUsage: 'API Usage',
        statLocalUsage: 'Local Usage',

        // Admin - verify log
        logTotal: 'Total',
        logEntries: 'entries',
        logSuccess: 'Success',
        logFailed: 'Failed',
        logNoRecords: 'No verification records',

        // Admin - telegram bot sections
        tgStats: '📊 Stats',
        tgVerifyLog: '📋 Verify Log',
        tgConfig: '⚙️ Config',
        tgServices: '📋 Services',
        tgUsers: '👥 Users',
        tgOrders: '💰 Orders',
        tgNoBotLog: 'No bot verification records',

        // Admin common
        loading: '⏳ Loading...',
        save: 'Save',
        saving: 'Saving...',
        refresh: '🔄',

        // Layout & CDK Redeeming
        redeemCreditsSuccess: '✅ Success! +{credits} credits',
        networkError: 'Network error, please try again',
        creditsBalance: 'Credits Balance',
        redeemCreditsTitle: '🎁 Redeem Credits',
        redeemBtn: 'Redeem',
        purchaseCreditsTitle: '🛒 Buy Credits',
        inviteFriends: 'Invite Friends',
        inviteBtn: 'Invite',
        inviteFriendsEarn: '🎁 Refer Friends to Earn Credits',
        inviteDesc: 'Receive <strong>+0.2 credits</strong> when friends register and buy credits through your link.',
        copied: '✓ Copied',
        copy: 'Copy',
        invitedCountLabel: 'Invited',
        earnedCreditsLabel: 'Credits Earned',
        recentInvites: 'Recent Referrals',
        rewardedStatus: '✓ Rewarded',
        pendingStatus: 'Pending',
        noInvitesYet: 'No referrals yet. Share your link with friends! 🚀',
        loginToInvite: 'Log in to get your referral link',
        apiDocsLink: 'API Docs',
        customerServiceTitle: 'Support',
        contactCustomerService: 'Contact Support',
        scanQrContact: 'Scan QR code to contact support',
        csAccountLabel: 'Support ID',

        // Verify Page
        tutorialsAndErrors: 'Tutorials & Common Errors',
        tutorialBindCardBtn: 'Binding Tutorial ▸',
        commonErrorsWarning: '⚠️ Common errors are not enabling 2FA or not deleting billing profiles',
        gptRechargeWaitNote: 'Credits will be deducted after recharge. Please wait patiently.',

        // Home (Login/Register) Page
        forgotLinkSent: 'Reset link has been sent to your email',
        forgotLinkFailed: 'Failed to send, please try again later',
        featureCreditsTitle: 'Account Credits System',
        featureCreditsDesc: 'Purchase CDK codes to redeem credits to your account. Managed in one place, deducts as you use.',
        featureVerifyDesc: 'Batch submit Google accounts and the system will automatically begin verification.',
        featureGptDesc: 'Recharge ChatGPT Plus accounts with one click and get automated upgrades.',
        featureInviteTitle: 'Referral Rewards',
        featureInviteDesc: 'Invite friends to register, both parties can get reward credits.',
        heroBadgeText: 'Leading Verification Automation Platform',
        heroTitleText: 'Batch Automation Verification Tool',
        heroDescText: 'One-stop Google One student verification & GPT recharge platform. Register and redeem CDK codes to use.',
        statVerified: 'Verified',
        statRate: 'Success Rate',
        statServices: 'Online Services',
        loginTab: 'Log In',
        registerTab: 'Sign Up',
        usernameLabel: 'Username',
        usernamePlaceholder: 'Enter username',
        emailPlaceholder: 'Enter email',
        passwordPlaceholder: 'Enter password',
        invitePlaceholder: 'Referral Code (Optional)',
        btnRegister: 'Create Account',
        forgotPasswordBtn: 'Forgot Password?',
        resetPasswordTitle: '🔑 Reset Password',
        resetPasswordDesc: 'Enter your registered email and we will send you a reset link',
        cancelBtn: 'Cancel',
        sendingBtn: 'Sending...',
        sendResetLinkBtn: 'Send Reset Link',
        stepRegisterTitle: '1. Register / Log In',
        stepRegisterDesc: 'Create your OnePASS account, with all credits and records managed in one place',
        stepRedeemTitle: '2. Buy & Redeem CDK',
        stepRedeemDesc: 'Purchase CDK codes and redeem them to your account, system auto-deducts',
        stepSubmitTitle: '3. Submit Verify / Recharge',
        stepSubmitDesc: 'Choose the service you want, input details, system handles the rest',

        // Profile Page
        tabPersonalInfo: 'Personal Info',
        tabQuotaHistory: 'Quota Records',
        tabVerifyRecords: 'Verify Records',
        tabSecuritySettings: 'Security',
        alertPasswordsMismatch: 'Passwords do not match',
        alertPasswordLength: 'Password must be at least 6 characters',
        alertPasswordSuccess: 'Password changed successfully',
        roleAdmin: '👑 Admin',
        roleUser: '👤 Regular User',
        roleAdminLabel: 'Admin',
        roleUserLabel: 'Regular User',
        quotaBalance: 'Quota Balance',
        totalVerificationsLabel: 'Total Verified',
        basicInfoTitle: '👤 Basic Info',
        regTime: 'Registration Time',
        quotaUsageHistoryTitle: '🎫 Quota Usage Records',
        currentBalanceUnit: 'Balance: <strong>{credits} times</strong>',
        thDate: 'Date',
        thAction: 'Action',
        thChange: 'Change',
        thBalance: 'Balance',
        timesUnit: 'times',
        regGift: 'Registration Gift',
        rechargeAction: 'Recharge',
        thVerifyId: 'Verification ID',
        thStatus: 'Status',
        thTime: 'Time',
        editBtn: 'Edit',
        exitBtn: 'Log Out',
        changePasswordTitle: '🔐 Change Password',
        confirmChangeBtn: 'Confirm',
        labelCurrentPassword: 'Current Password',
        labelNewPassword: 'New Password',
        labelConfirmNewPassword: 'Confirm New Password',

        // Recharge Page
        rechargeSuccessAlert: 'Recharge success! Received {quota} quota times',
        rechargeQuotaTitle: '💰 Recharge Quotas',
        rechargeQuotaDesc: 'Choose the plan that suits you to get verification quotas',
        currentBalanceLabel: 'Current Balance',
        mostPopular: '🔥 Most Popular',
        buyNowBtn: 'Buy Now',
        whyChooseRechargeTitle: 'Why choose our recharge service?',
        featureInstantTitle: 'Instant Credit',
        featureInstantDesc: 'Once payment is complete, credits are added instantly to your account.',
        featureSecureTitle: 'Secure Payment',
        featureSecureDesc: 'Official payment channels are used to ensure the safety of your funds.',
        featureDiscountTitle: 'Bulk Discounts',
        featureDiscountDesc: 'Bulk packages enjoy higher discounts. More verify, more savings.',
        featureCsTitle: '7x24 Customer Support',
        featureCsDesc: 'Our support team is always ready to answer any questions.',
        confirmOrderTitle: 'Confirm Order',
        payableAmount: 'Payable Amount',
        selectPaymentMethod: 'Select Payment Method',
        alipay: 'Alipay',
        wechatPay: 'WeChat Pay',
        processingPayment: 'Processing payment...',

        // Bypass Page
        connectError: 'Connection error: {error}',
        executing: 'Executing...',
        startBypass: 'Start Bypass',
        uploadCount: 'Successfully uploaded {uploads} time(s)',
        linkAlreadySuccess: 'Link is already in success status',
        bypassFailed: 'Bypass failed',
        waitingOp: 'Waiting for action...',

        // Maintenance Page
        underMaintenance: 'Under Maintenance',
        maintenanceMsg: 'System is undergoing maintenance, please try again later',
        etaLabel: 'Estimated recovery time: {time}',
        maintenanceSub: 'We are performing system upgrades, please visit again later',

        // ResetPassword Page
        resetPasswordAlertLength: 'Password length cannot be less than 6 characters',
        resetPasswordAlertMismatch: 'Passwords do not match',
        resetPasswordFailed: 'Reset failed',
        invalidResetLinkTitle: 'Invalid Reset Link',
        invalidResetLinkDesc: 'Please click the reset link in your email again, or request another reset',
        btnGoToLogin: 'Go to Login',
        setNewPasswordTitle: 'Set New Password',
        setNewPasswordDesc: 'Please enter your new password',
        resetSuccessTitle: 'Password Reset Successful!',
        resetSuccessDesc: 'Your password has been updated. Please log in with your new password.',
        goToLoginBtn: 'Go to Login',
        newPasswordLabel: 'New Password',
        min6Chars: 'At least 6 characters',
        confirmNewPasswordLabel: 'Confirm New Password',
        inputNewPasswordAgain: 'Enter new password again',
        resetPasswordBtn: 'Reset Password',
        backToLoginBtn: 'Back to Login',
    }
};

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => {
        return localStorage.getItem('verifykey-lang') || 'zh';
    });

    const toggleLang = () => {
        setLang(prev => {
            const next = prev === 'zh' ? 'en' : 'zh';
            localStorage.setItem('verifykey-lang', next);
            return next;
        });
    };

    const t = (key) => translations[lang]?.[key] || translations['zh'][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLang = () => useContext(LanguageContext);
